website:
  title: "Személy- és járműforgalmi jelentés OSAP 1222"
  favicon: "https://map.ksh.hu/timea/images/shortcut.ico"
  image: "https://map.ksh.hu/timea/images/shortcut.ico"
  open-graph:
    site-name: "Személy- és járműforgalmi jelentés OSAP 1222"



